apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
stringData:
  SECRET_KEY: "@e2(yx(v&tgh3_s=0yja-h!dpebxsz^dg47x)-k&kq_3zf*9e*"
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_USER: todo
  MYSQL_PASSWORD: todo123

  NAME: todo
  USER: todo
  PASSWORD: todo123
  HOST: mysql-0.mysql